### ISSUE TITLE
Offer pre-built binaries

### ISSUE THREAD

**Issue by CreepySkeleton** [crate-ci/cargo-release#201]
Currently, the only way to install `cargo-release` is `cargo install` which builds it from scratch, incudind all the dependencies. No wonder it takes quite a bit of time.

You can setup your travis CI to deploy prebuilded binaries to your `releases` page so people are able to download it from there. The most easy way to do that is to use [`trust`](https://github.com/japaric/trust/). What do you think?

**Comment by epage** [comment]
Yes, this would be a big help for users, especially if its [install.sh](https://github.com/crate-ci/gh-install) compatible 

Personally, I had a lot of problems with trust because you fork it, make changes, and then have to port trust changes over.  That last part made me give up on it.

For my `[bin]` projects, I've switched to Azure Pipelines and it isn't too bad for defining artifacts and uploading them to github releases
https://github.com/crate-ci/typos/blob/master/azure-pipelines.yml

I've not yet played with Github Actions to see what that experience is like.

**Comment by CreepySkeleton** [comment]
>you fork it, make changes, and then have to port trust changes over. 

Why so complex? Just copy the `ci` folder and `.travis.yml` files (probably also `appveyor.yml` but I'm pretty sure it can be removed if you don't want it), and then edit `travis.yml` to meet your needs, that's all. Or at least this is what [their doc](https://github.com/japaric/trust/#use-this-template) says.

**Comment by epage** [comment]
The docs don't say "just edit travis.yml` but:

> You'll have to adjust those files to meet your needs. Just look inside those files for comments that start with the word TODO; they'll tell you want needs to be changed.

There are TODOs throughout the CI folder.

I adopted a project using trust.  I tried to update to the latest trust multiple times and failed.  Rather tools be provided that people can glue together than a template that is hand managed.  Less update problems.

**Comment by epage** [comment]
We now have pre-built binaries: https://github.com/crate-ci/cargo-release/releases/tag/v0.16.6
