### ISSUE TITLE
`--skip-published` flag

### ISSUE THREAD

**Issue by epage** [crate-ci/cargo-release#303]
`cargo-workspace` has this.  It sounds like it'd help with recovery but I'm also a bit unsure how to apply it.   It'd help with the `cargo release` (no bump) case.

**Comment by oovm** [comment]
Any progress for this feature?

**Comment by epage** [comment]
> I searched error message and didn't find the relevant error handling code.

That error is coming from `cargo publish`.

What would be needed here is to use `crates_index` to check if the version is already published and then completely skip the publish step.

What is the situation you've run into this that this would be helpful?  I noted this as something in cargo-workspace but the use case is one I'm a bit fuzzier on which helps in prioritization and design.

**Comment by oovm** [comment]
My use case is like this. 

Ideally, it should automatically identify all the sub-projects that commit commits in the workspace, and then bump them (and in-project dependences) and try publish.

(For example, [cranko](https://github.com/pkgw/cranko) can distinguish how many changes have occurred in each sub-project and update CHANGELOG)

Because cargo-publish does not automatically recognize which versions need bumps, I will do this manually.
Then in fact, most of the sub-items have not changed, so you need to skip.

---

Of course, a lazy solution is to use the same version number, and any small changes will bump all.

It sounds like ddos package manager server...:rofl:

**Comment by epage** [comment]
So identifying what all packages have changes and skipping unchanged sounds like https://github.com/crate-ci/cargo-release/issues/298

I feel like there is something I missed in your explanation.  With `cargo-release`, a user says what version to release (using an absolute or relative target version), we then run through the release process for that, including publishing, tagging, and pushing.  We support a `release` flag to not bump the current version but release it as-is (usually for recover purposes).  When is it you'd want to pass `--skip-published` in your work flow?

**Comment by oovm** [comment]
For me, if you can accurately bump the changed version & depend version, then this feature is unnecessary.

**Comment by epage** [comment]
> For me, if we can accurately bump the changed version & internal dependency version, then this feature is unnecessary.

Say we don't do #298, when would this feature be necessary?  I'm trying to understand what you've seen about it that helps with issues similar to #298

**Comment by epage** [comment]
I think #393 is probably the most we'll do for this issue.

**Comment by levkk** [comment]
Late to the party, but I think you can just do something like this:

```bash
CRATE="$(cargo read-manifest | jq '.name' -r)"
VERSION="$(cargo read-manifest | jq '.version' -r)"

test $(cargo search "$CRATE" | grep "$CRATE =" | awk '{print $3}') != "\"$VERSION\""
```

Not as pretty as a CLI flag, of course.
