### ISSUE TITLE
Verification build fails because it happens before version bump

### ISSUE THREAD

**Issue by kpcyrd** [crate-ci/cargo-release#335]
With the lastest version I had to update my release command from:
```
cargo release 0.13.0
```
to:
```
cargo release 0.14.0 --workspace --no-verify --execute
```
The test build fails because it's resolving this dependency:
```
rebuilderd-common = { version= "=0.13.0", path="../common" }
```
to "rebuilderd-common 0.13.0 from crates.io" instead of the code that I intend to release as 0.14.0 in `../common`.

I'm not sure what's a good way to solve this unfortunately.

**Comment by epage** [comment]
Is it the verify step that is failing (ie what you disable with `--no-verify`?  Does it fail in both dry-run and `--execute` mode?

Since we started running `cargo publish --dry-run` during dry-run mode, we will fail if there is a dependency on something being released as part of the current batch and you can restore the old behavior if you add `--skip-publish` when doing a dry-run.

Probably something for us to detect and automatically skip the publish verify, with a warning, when there is a dependency being released as part of the batch.

**Comment by epage** [comment]
Our options
- Tell people to pass `--no-verify` or `--no-publish` in this case
- Detect this case and do the above on behalf of the users
- Go back to dry-run not running publish
