### ISSUE TITLE
Explicit version specifications mishandled with `-p` specifier

### ISSUE THREAD

**Issue by benesch** [crate-ci/cargo-release#370]
Suppose you have a workspace containing:

   * Crate `slow` at v1.0.0
   * Crate `speedy` at v2.0.0

Attempting to bump `slow` to v1.1.0 via an explicit version specification incorrectly fails with cargo-release v0.18.6:

```
$ cargo release -p slow 1.1.0
Fatal: Support for modifying Cannot release version smaller than current one is currently unsupported
```

Note that invoking cargo-release with the "minor" instruction, rather than the explicit version "v1.1.0", works fine:

```
$ cargo release -p slow minor
```

The bug is a result of cargo-release asking the question "is 1.1.0 a valid version?" for every crate in the graph, not just those that are filtered by the -p argument. When you specify "minor" instead of "1.1.0", cargo-release instead computes a separate minor version bump for each crate in the graph (v1.1.0 for slow and v2.1.0 for speedy).

I've packaged this up as a minimal reproduction with instructions: https://github.com/benesch/cargo-release-bug

I put together a proof-of-concept fix in this (now closed) PR: https://github.com/crate-ci/cargo-release/pull/369.

**Comment by epage** [comment]
> The bug is a result of cargo-release asking the question "is 1.1.0 a valid version?

Thank you for the re-wording.  #369 discussed bumping the skipped crates which, to me, implied doing more than just checking the new version.

**Comment by epage** [comment]
This broke in #357 when we started reporting more details on excluded packages

**Comment by benesch** [comment]
> > The bug is a result of cargo-release asking the question "is 1.1.0 a valid version?
> 
> Thank you for the re-wording. #369 discussed bumping the skipped crates which, to me, implied doing more than just checking the new version.

Oh good! It was hard to word. The function that does the validation is [`TargetVersion::bump`](https://github.com/crate-ci/cargo-release/blob/26afe9be5fc881c9dd24fcc9a7528dd6cdcb1f10/src/version.rs#L13-L43); of course the "bump" is just in-memory and gets discarded for excluded packages.

> This broke in #357 when we started reporting more details on excluded packages

Ah, gotcha. I'm sure there's a much cleaner refactoring than plumbing the `bool` like I did in #369, but I'm probably not the guy to come up with it.

(By the way, unrelated to any of this, but we're super excited about clap v3 over at @MaterializeInc! Appreciate all the work that you're putting in here and there!)

**Comment by epage** [comment]
> (By the way, unrelated to any of this, but we're super excited about clap v3 over at @MaterializeInc! Appreciate all the work that you're putting in here and there!)

Thanks!

So this came about because we reused the bump data generation from actual releasing for when we report potential issues with what was skipped.

So the first problem is we shouldn't be reporting any errors from that code path!  Unlike dry-run where these errors represent real problems the user needs to know, any error is more of a programming mistake and shouldn't block the user.  Instead of us failing on the first error and exit, we should iterate over the error with the excluded package data and log it, moving on to the next excluded package.

Once that is done, we'll be erroring, instead of reporting information for the user.  Ideally, we'd not be over-reusing logic but that'd take more work to re-work.  The bool approach was a good attempt at addressing this problem though I think what will work better is if we did a `args.clone()` and turned off bumping for the exclude iteration.  This will reuse existing mechanisms and keep the code clear.

If someone is willing to take this up, feel free.  If there are questions on part, I can expand.  Otherwise, I can get to this by early next week at the latest.

**Comment by epage** [comment]
> The function that does the validation is TargetVersion::bump; of course the "bump" is just in-memory and gets discarded for excluded packages.

Yeah, I saw where the wording came from and understand how the comfusion came about because of it!

**Comment by epage** [comment]
Fix is released.

**Comment by benesch** [comment]
Woohoo, thanks very much @epage!
