### ISSUE TITLE
publish = false crates get git release tags

### ISSUE THREAD

**Issue by kornelski** [crate-ci/cargo-release#399]
In https://github.com/kornelski/rust-security-framework I have internal crates for testing (systest, ios-shim). These crates have `publish=false` in `Cargo.toml`, and I'd like `cargo-release` to *completely* ignore their existence. I haven't found any way to explicitly ignore crates, other than `publish=false`. The problem is that even with `publish=false`, it still creates `systest/0.1.0` tag and pushes it to the git repo.

**Comment by epage** [comment]
We offer [`release = false`](https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md#config-fields) for this purpose ([example](https://github.com/crate-ci/typos/blob/master/crates/typos-dict/codegen/Cargo.toml#L13)).

`publish` intentionally only controls whether to call `cargo publish` so people can use the rest of the logic if they want (like some do with `[[bin]]`s).

**Comment by kornelski** [comment]
I think it would be nice if the default `release` was `release = $publish`, so that if someone wants (IMHO very unusual) tagging of un-released crates then they opt-in, instead of everyone else needing to opt-out.

**Comment by epage** [comment]
This is an interesting case where discoverability is dependent on the user and needs to be balanced with convenience.

Our options
- Release is independent of `publish`
- ~~Release defaults to `Cargo.toml`'s `publish`~~
  - Ruled out because ideally people only use the `Cargo.toml` field to be very sure that they are not publishing
- Release defaults to `publish`

Our users
- ~~Those using the registry for everything~~ (any change won't impact them, so we can ignore them)
- Those mixing a registry with unreleased crates (e.g. xtasks)
  - Assumption: users going this route do not need to "release" the unpublished crates
- Those not using a registry (e.g. distributed through git, some bins)
- Those not using a registry (e.g. distributed through git, some bins) and with unreleased crates

User perspectives
- Those who conflate `publish` with `release`
- Those who recognize "publish" as a step in a "release" process

Something to keep in mind is that the default behavior is for dry-run.

For the mixed use case, when first adopting cargo-release or when first using a mixed workspace,
1. you'll start with `publish = false` in the manifest to be safe.
2. you run `cargo-release --all` and see it wanting to release unpublished crates
3. you look up in the docs how to configure this and set it

For the non-registry use case, when first adopting cargo-release or when first creating a non-registry crate
1. you'll start with `publish = false` in the manifest to be safe
2. Everything works

Now if you add unreleased crates in, 
1. you'll start with `publish = false` in the manifest to be safe and realize it will be published like your other crates and 

This script basically runs the opposite way (in complexity) when changing the default.  So that leaves us with
- Which is more discoverable?
- Which is more understandable? (this is different and deals with frustration in the discovery process)
- Which is more convenient?
- Who should we optimize for and by how much?

Side notes
- `cargo release --dump-config -` can help to a degree (1) if people realize it exists and (2) the values are predictable based on the field name (since it only shows one crate in a workspace and not all)
  - This makes me lean towards the current behavior.  Having a dynamic default makes it harder to predict behavior.

**Comment by kornelski** [comment]
I'll add that I know how Cargo behaves, and familiar with `publish`, but I'm new to `cargo release`, and have no idea what metadata it supports, or that `--dump-config` even exists.

**Comment by epage** [comment]
After getting more experience with this, I'm regretting this and reverted it in #597.  See that PR for more details
