### ISSUE TITLE
Releasing a workspace duplicates pre-release-replacments

### ISSUE THREAD

**Issue by Jake-Shadle** [crate-ci/cargo-release#470]
When doing a workspace release like this:

```
cargo release --workspace --execute 0.3.1
```

with a config like this:

```ini
pre-release-commit-message = "Release {{version}}"
tag-message = "Release {{version}}"
tag-name = "{{version}}"
shared-version = true
consolidate-commits = true
consolidate-pushes = true
pre-release-replacements = [
    { file = "../CHANGELOG.md", search = "Unreleased", replace = "{{version}}" },
    { file = "../CHANGELOG.md", search = "\\.\\.\\.HEAD", replace = "...{{tag_name}}" },
    { file = "../CHANGELOG.md", search = "ReleaseDate", replace = "{{date}}" },
    { file = "../CHANGELOG.md", search = "<!-- next-header -->", replace = "<!-- next-header -->\n## [Unreleased] - ReleaseDate" },
    { file = "../CHANGELOG.md", search = "<!-- next-url -->", replace = "<!-- next-url -->\n[Unreleased]: https://github.com/EmbarkStudios/crash-handling/compare/{{tag_name}}...HEAD" },
]
```

Each replacement is duplicated by the number of crates that are being released.

See this commit for an example https://github.com/EmbarkStudios/crash-handling/commit/f1604161fcf6155dde411e80c845089df9ae3d3d

**Comment by epage** [comment]
Pre-release replacements are run for every crate that is released by design.  If you want them to run only for a specific crate, they should be put in that crate's specific `release.toml` / `Cargo.toml`.

Generally in a workspace, one crate is the user facing one that the changelog corresponds to or else the crates have crate-specific changelogs.  In both cases, there are crates associated with the changelog that should exclusively have the replacements configured for.
