### ISSUE TITLE
{{tag_name}} doesn't work in pre-release-replacements with --no-tag

### ISSUE THREAD

**Issue by DianaNites** [crate-ci/cargo-release#508]
{{tag_name}} doesn't work in pre-release-replacements with --no-tag, instead the literal text `{{tag_name}}` is substituted and no error or warning is displayed.

The behavior I expected here is that `--no-tag` stops cargo-release from creating a git tag, but that replacements using it still work, "as if" it had been made.

**Comment by epage** [comment]
It would be misleading for us to advertise that a tag name for a tag that likely doesn't exist.

Could you describe the use case for why you need access to the tag name, even if it doesn't exist?  Would it instead work to hard code the value in your configuration where needed?

**Comment by DianaNites** [comment]
My use-case was a "dry-run" to make sure replacements worked properly before actually committing and publishing anything.

I can also imagine use-cases that would want to use the "tag_name" identifier for something other than git tags, which would work fine if not the value depending on it actually existing on git.

I think cargo-release should use whatever tag_name it was going to, or it should error because its invalid to use `--no-tag` and have `{{tag_name}}` in replacements. `{{tag_name}}` is a tag name that doesn't exist too

**Comment by epage** [comment]
> My use-case was a "dry-run" to make sure replacements worked properly before actually committing and publishing anything.

In case you weren't aware, dry-run is the default and if you increase the verbosity level, you can see diffs of what the replacements will do.  Granted, browsing the actual filesystem can still be useful

I'll have to  think more on this because it does make sense to do trial runs.  I've done `--no-publish` before as I experiment.

> instead the literal text {{tag_name}} is substituted 
>
> it should error

cargo-release uses a very sloppy form of templates.  It ignores anything that looks like a variable that isn't.  There are pros and cons to this.  https://github.com/crate-ci/cargo-release/issues/116 further discusses templating
