### ISSUE TITLE
help: `error: object not found - no match for id`

### ISSUE THREAD

**Issue by Mathieu-Lala** [crate-ci/cargo-release#625]
First of all, a word of appreciation for your work and this project : it is superb !

But I have an issue on my release workflows : [last output](https://github.com/viridIT/vSMTP/actions/runs/3603008586/jobs/6070668740)
I am working on a workspace with member named `vsmtp-*` and I want a tag to be created when `vsmtp` is published.

But nothing is pushed, and there seems to have an error on the tag creation. Do you have any hint ?

**Comment by epage** [comment]
The error is
```
   Uploading vsmtp v1.4.0-rc.5 (/home/runner/work/vSMTP/vSMTP/src/vsmtp/vsmtp-core)
     Waiting on vsmtp to propagate to index
[2022-12-02T15:56:58Z DEBUG cargo_release::steps::tag] creating git tag vsmtp-v1.4.0-rc.5
error: object not found - no match for id (faaff3d3a174a33cb093b6aa37703fcce9ccfee6); class=Odb (9)
```

That is coming from git2.  The logged message happens immediately before we call `ops::git::tag` which is not yet using `git2` (hadn't taken the time yet to see how to do the signing).  So that means this actually failed during the push step.

`faaff3d3a174a33cb093b6aa37703fcce9ccfee6` is https://github.com/viridIT/vSMTP/commit/faaff3d3a174a33cb093b6aa37703fcce9ccfee6.  The error happened as part of viridIT/vSMTP#806. Its unclear why it cares about that commit.

The only thing I can think of is our "is_local_unchanged" check but that is very similar to our `verify_if_behind` check and shouldn't be failing.

I'll need to annotate the code with more checks to further deduce what is happening.

**Comment by Mathieu-Lala** [comment]
Here is the fix : https://github.com/viridIT/vSMTP/pull/846/files

```yaml
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
```

Seems like you need the full commit history (and not the last one taking by `actions/checkout` by default)
