### ISSUE TITLE
Replacements from workspace use path relative to a crate

### ISSUE THREAD

**Issue by max-sixty** [crate-ci/cargo-release#651]
Prior to [this commit](https://github.com/PRQL/prql/pull/2055/commits/a14db749777e7ff5e815f0401f881d5510a04bfd), running:

```
cargo release replace -x --no-confirm
```

raised an error:

```
error: unable to find file 
/Users/maximilian/workspace/prql/prql-compiler/book/src/language-features/target.md 
to perform replace
```

Note the `prql-compiler` part of the path — that surely shouldn't be there, since it should be using the root of the crate, rather than the `prql-compiler` path (I'm also not sure why it uses that crate rather than others?)

It's ofc possible I've made a foolish error, but I did try a couple of times.

The commit has the workaround — placing the replacement in a crate and referring to the path relative to the crate.

**Comment by epage** [comment]
So far, we've considered this expected behavior.  In part, this is because generally it would be a bug to have multiple crates updating the same file on release and instead you'd only want one (like a shared changelog).  In contrast, you might want to define reusable changelog replacements when there are multiple changelogs.

This also came up in #205.

Is there a reason you are wanting to do that replacement on every crate's release and not on a specific crate?

**Comment by max-sixty** [comment]
Ah OK, I see, thanks @epage 

> Is there a reason you are wanting to do that replacement on every crate's release and not on a specific crate?

We only do one release for all crates, and this replacement didn't strictly belong in one of them.

I think the current state is fine for functionality. I did find the semantics a bit confusing, but on reflection can see why it acts as an inherited property rather than a separate entity. I can't think of any bright ideas beyond documenting it...

I'll close! Thanks as ever.
