### ISSUE TITLE
Suggested workflow for going through a PR instead of pushing to the default branch?

### ISSUE THREAD

**Issue by jyn514** [crate-ci/cargo-release#658]
I have a project that disallows (with branch protections) pushing to the `master` branch. As a result, any new commits or tags need to go through a PR instead (and get review approvals, pass CI, etc). Unfortunately, this doesn't seem to combine well with cargo-release. Consider a naive approach:

```
git checkout -b release-0.1.0
cargo release
# create/review/merge a PR to master
```
If any PRs are merged to master before `release-0.1.0`, then the published release and tag will not actually correspond to any commit on master.

Now, it's possible to instead separate this into two parts, one where cargo-release bumps the version and changelog, and another where it runs the actual publish and tag:
```
cargo release --no-publish --no-tag  # run locally
# create/review/merge the PR
cargo publish && git tag v0.1.0 # run in CI for the master branch
```
but there's still a race condition between creating and merging the PR: if other PRs are merged in the meantime, the CHANGELOG will be incorrect. You could move more of the steps into CI for the master branch, but then you have to create automatic commits on master which seems very sketchy and means they aren't reviewed by anyone.

One scheme I came up with was to create a CI job that disallows people from merging the release PR if the latest commit doesn't have a tag (e.g. looking for `(cargo-release)` in the PR description), but that
- requires branch protections that disallow merging branches that aren't fully up-to-date with master (i.e. no rebasing and or merge commits)
- requires you to use "rebase and merge" in github, not "squash" or "create a merge commit"; and clicking the wrong button just silently does the wrong thing instead of giving an error, because CI won't run for the tagged commit. This is especially bad because of the requirement for branches not to rebase over master above; I'm not aware of an out-of-the-box way to do this with github actions.

---

This all seems rather complicated and I'm surprised it's not mentioned in the FAQ. Has anyone tried to do this before?

**Comment by epage** [comment]
> If any PRs are merged to master before release-0.1.0, then the published release and tag will not actually correspond to any commit on master.

Isn't this only true if you squash?  If you do a merge-commit, then it will exist.  We already want to support creating the merge commit for the local case for #147.

Granted, I dislike the idea if publishing something that isn't "live" or about to be live.  Technically, a gate like a PR means you could get rejected.  If not, what is the reason for disallowing non-force pushes from the same people who have publish permission?  To avoid those people don't push in other cases?  If they have publish permissions, I personally question that level of strictness.

If merge-commits are allowed, another possible option is to support publishing/tagging a non-HEAD commit so you can look up the intended-to-publish commit and run it there.  The commit will be on its own branch of the history that does not include anything merged since the branch was created.
