### ISSUE TITLE
Failure to publish a package leaves Cargo.toml version updated

### ISSUE THREAD

**Issue by link2xt** [crate-ci/cargo-release#664]
I ran `cargo release minor`, it updated Cargo.toml from v0.7.0 to v0.8.0 but then failed to actually publish due to network/authentication error. I logged into crates.io and tried to run `cargo release minor` again, but then it prompted to release v0.9.0 even though v0.8.0 was not successfully published yet. I had to resort to publishing manually using `cargo publish`.

There is a similar issue about checking for publishing permissions in advance: #601

I do not have a solution, maybe I should just use `cargo release v0.8.0` instead of `cargo release minor`. Ideally `cargo release minor` should be transactional/atomic, if it fails to publish, it should revert updates to Cargo.toml too.

**Comment by epage** [comment]
A couple of challenges
- The error might happen in the middle of publishing multiple packages
- We'd need to delete the entire commit we created, not just undo a file, because of pre-release replacements
- We don't know what all a user might have done in pre-release hooks

We could specialize some of these cases but it makes the behavior less predictable.  The current approach allows for inspecting of the failed state and different forms of error recovery (e.g. just run `cargo release` if there was an authentication failure).

As the design was intentional for error recovery and solving this (if we changed error recovery) would be hard due to the non-atomic nature, I'm included to close this.
